import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    width: '85%',
    backgroundColor: '#f0f0f0',
    borderRadius: 15,
    padding: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    paddingTop: 20,
    paddingBottom: 20,
  },
  title: {
    textAlign: 'center',
    fontSize: 25,
    fontWeight: 'bold',
    marginTop: 5,
    marginBottom: 10,
  },
  input: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  inputArea: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    width: '90%',
    height: 40,
    borderColor: '#e6aaa9',
    borderWidth: 2,
    borderRadius: 5,
  },
  inputType: {
    width: '100%',
    textAlign: 'left',
    marginBottom: 5,
    marginLeft: 35,
  },
  textInput: {
    flex: 1,
    width: '100%',
    paddingTop: 5,
    marginRight: 5,
    paddingBottom: 5,
    marginLeft: 5,
    backgroundColor: '#fff',
    color: '#424242',
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginRight: 15,
  },
  buttonCancel: {
    height: 30,
    paddingRight: 10,
    paddingLeft: 10,
    flexDirection: 'row',
    backgroundColor: '#0B2161',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 15,
    borderRadius: 5,
  },
  buttonSave: {
    height: 30,
    paddingRight: 10,
    paddingLeft: 10,
    flexDirection: 'row',
    backgroundColor: '#fe4e4b',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginLeft: 20,
    borderRadius: 5,
  },
  buttonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  errorMessage: {
    textAlign: 'center',
    color: '#ec3237',
    fontWeight: 'bold',
    marginBottom: 10,
  },
});

export default styles;
