import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    width: '90%',
    alignItems: 'flex-end',
  },
  card: {
    width: '96%',
    marginRight: '2%',
    backgroundColor: '#f0f0f0',
    marginTop: 20,
    alignItems: 'center',
    borderRadius: 15,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    paddingTop: 40,
    paddingBottom: 5,
    position: 'relative',
    zIndex: 1,
  },
  buttonExit: {
    height: 35,
    width: 35,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 11,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    backgroundColor: '#fff',
    marginRight: 40,
    position: 'absolute',
    zIndex: 2,
  },
  buttons: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginTop: 20,
  },
  button: {
    height: 40,
    flexDirection: 'row',
    alignSelf: 'stretch',
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 15,
    borderRadius: 5,
  },
  buttonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
});

export default styles;
